#!/bin/bash
export AWS_ACCESS_KEY_ID="xxxxxxxx"
export AWS_SECRET_ACCESS_KEY="xxxxxxxxxxxxxxxx"
export PASSPHRASE="xxxxxx"
export REGION_NAME="us-west-1"
export bucket="com.xxxxx.backup"
export eraseafter="1M"
export fullifolderthan="7D"
export OLDERTHAN="365"
export MAILADDR="xxxxx@gmail.com"
export mailfrom="xxxxxxxp@xxxxx.com"